=== michael-sevcik/NPRG036-Data-Formats/3_vlado/3/xml/schemas/schema-1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="https://www.w3.org/2009/01/xml.xsd" />



<xs:element name="Dormitory">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="name"/>
            <xs:element ref="address"/>
            <xs:element ref="tenants"/>
            <xs:element ref="cafeterias"/>
        </xs:sequence>
        <xs:attribute name="id" use="required"/>
    </xs:complexType>
</xs:element>

<xs:element name="Student">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="givenName"/>
            <xs:element ref="familyName"/>
            <xs:element name="studyYear" type="xs:integer"/>
            <xs:element ref="nicknames"/>
        </xs:sequence>
        <xs:attribute name="id" use="required"/>
    </xs:complexType>
</xs:element>

<xs:element name="Cafeteria">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="name"/>
            <xs:element ref="address"></xs:element>
        </xs:sequence>
        <xs:attribute name="id" use="required"/>
    </xs:complexType>
</xs:element>



<xs:element name="dormitories">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="Dormitory" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="tenants">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="Student" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="cafeterias">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="Cafeteria" minOccurs="0" maxOccurs="1"></xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="nicknames">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="nickname" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>



<xs:element name="name">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>

<xs:element name="address">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>

<xs:element name="givenName">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>

<xs:element name="familyName">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>

<xs:element name="nickname">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>

</xs:schema>

=== michael-sevcik/NPRG036-Data-Formats/3_vlado/3/xml/data/data-1.xml
<?xml version="1.0" encoding="utf-8"?>


<dormitories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./../schemas/schema-1.xsd">

<Dormitory id="trojaKolej">
    <name xml:lang="cs">Kolej 17. Listopadu</name>
    <address xml:lang="cs">Pátkova 3, 180 00 Praha 3, Česko</address>
    <tenants>
        <Student id="rameshs">
            <givenName xml:lang="en">Samyuktha</givenName>
            <familyName xml:lang="en">Ramesh</familyName>
            <studyYear>3</studyYear>
            <nicknames>
                <nickname xml:lang="en">Samy</nickname>
            </nicknames>
        </Student>
    </tenants>
    <cafeterias>
        <Cafeteria id="trojaMenza">
            <name xml:lang="cs">Menza 17. Listopadu</name>
            <address xml:lang="cs">Pátkova 3, 180 00 Praha 3, Česko</address>
        </Cafeteria>
    </cafeterias>
</Dormitory>

<Dormitory id="svehlovka">
    <name xml:lang="cs">Kolej Švehlova</name>
    <address xml:lang="cs">Slavíkova 22, 120 00 Praha 3, Česko</address>
    <tenants>
        <Student id="vozarv">
            <givenName xml:lang="cs">Vladimír</givenName>
            <familyName xml:lang="cs">Vozár</familyName>
            <studyYear>2</studyYear>
            <nicknames>
                <nickname xml:lang="sk">hhehe</nickname>
                <nickname xml:lang="en">hoho</nickname>
            </nicknames>
        </Student>
    </tenants>
    <cafeterias/>
</Dormitory>

<Dormitory id="frantuvPokoj">
    <name xml:lang="cs">Frantův Pokoj</name>
    <address xml:lang="cs">Pátečná 8, 000 15 Frantovo, Česko</address>
    <tenants>
        <Student id="frantikf1">
            <givenName xml:lang="cs">Freda</givenName>
            <familyName xml:lang="cs">Frantik</familyName>
            <studyYear>6</studyYear>
            <nicknames>
                <nickname xml:lang="cs">Franta</nickname>
            </nicknames>
        </Student>
    </tenants>
    <cafeterias>
        <Cafeteria id="uFranty">
            <name xml:lang="cs">Hostinec u Franty</name>
            <address xml:lang="cs">pod Lípou 17, 000 15 Frantovo, Česko</address>
        </Cafeteria>
    </cafeterias>
</Dormitory>

<Dormitory id="skutocnanka">
    <name xml:lang="sk">Skutočný Internát</name>
    <address xml:lang="sk">Ulicová 7, 821 01 Bratislava, Slovensko</address>
    <tenants>
        <Student id="umudrenak">
            <givenName xml:lang="cs">Katka</givenName>
            <familyName xml:lang="cs">Umúdrená</familyName>
            <studyYear>2</studyYear>
            <nicknames>
                <nickname xml:lang="sk">Kata</nickname>
            </nicknames>
        </Student>
    </tenants>
    <cafeterias/>
</Dormitory>

</dormitories>
